# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Verify installed packages
      run: |
        # Debugging step to ensure dependencies are installed
        python -m pip freeze
    - name: Analyse the code with pylint
      run: |
        # Explicitly invoke pylint with python -m
        python -m pylint --disable=C0413 $(git ls-files '*.py')
    - name: Autoformat code
      run: |
        # Autoformat code with Black and sort imports with isort
        pip install black isort
        black .
        isort .
    - name: Test with pytest
      run: |
        pytest testing/
