# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev libatlas-base-dev gfortran
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas --force-reinstall
        pip install flake8 pytest numpy torchvision torch tensorflow pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Verify installed packages
      run: |
        python -m pip freeze
    - name: Autoformat and sort imports
      run: |
        pip install black isort
        black .
        isort .
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with pylint
      run: |
        python -m pylint --disable=C0413 $(git ls-files '*.py')
    - name: Test with pytest
      run: |
        pytest testing/
